x-superset-image: &superset-image apachesuperset.docker.scarf.sh/apache/superset:${TAG:-latest}
x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes:
  &superset-volumes # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - superset_home:/app/superset_home

version: "3.7"
services:
  redis:
    image: redis:7
    container_name: superset_cache_2
    restart: unless-stopped
    volumes:
      - redis:/data

  db:
    env_file: .env
    image: postgres:15
    container_name: superset_db_2
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  superset:
    env_file: .env
    # image: *superset-image
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: superset_app_2
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    ports:
      - 8090:8088
    depends_on: *superset-depends-on
    volumes: *superset-volumes

  superset-init:
    # image: *superset-image
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: superset_init_2
    command: ["/app/docker/docker-init.sh"]
    env_file: .env
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true

  superset-worker:
    # image: *superset-image
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: superset_worker_2
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: .env
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]

  superset-worker-beat:
    # image: *superset-image
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: superset_worker_beat_2
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file: .env
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false
